server:
  port: 9090

spring:
  application:
    name: ms-kafka
  kafka:
    bootstrap-servers: localhost:29093,localhost:39093,localhost:49093
    streams:
      properties:
        schema.registry.url: http://localhost:8081
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        commit.interval.ms: 5000
        state.dir: /tmp/kafka-streams
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
    properties:
      specific.avro.reader: false
      auto.register.schemas: true
      schema.registry.url: http://localhost:8081
    security:
      protocol: SSL
    ssl:
      trust-store-location: classpath:kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: classpath:kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123
#  cloud:
#    stream:
#      bindings:
#        input-channel-1:
#          destination: users
#      kafka:
#        streams:
#          binder:
#            application-id: mykafka
#            brokers: localhost:9092
#            configuration:
#              default:
#                key:
#                  serde: org.apache.kafka.common.serialization.Serdes.StringSerde
#                value:
#                  serde: org.apache.kafka.common.serialization.Serdes.StringSerde